# Generated by Django 2.1 on 2021-01-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201223_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborater',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='collaboraters', to='app.Competence'),
        ),
    ]
