# Generated by Django 2.1 on 2021-01-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210106_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborater',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='collaborater',
            name='level',
        ),
        migrations.RemoveField(
            model_name='collaborater',
            name='workstation',
        ),
    ]
