# Generated by Django 2.1 on 2021-01-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210106_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborater',
            name='workstation',
            field=models.ManyToManyField(blank=True, related_name='collaboraters', to='app.ListWorkStation'),
        ),
        migrations.AddField(
            model_name='competence',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='competences', to='app.ListInterest'),
        ),
        migrations.AddField(
            model_name='competence',
            name='level',
            field=models.ManyToManyField(blank=True, related_name='competences', to='app.ListLevel'),
        ),
    ]
