# Generated by Django 2.1 on 2021-01-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210106_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborater',
            name='Society',
            field=models.CharField(max_length=200, verbose_name='société'),
        ),
    ]
