# Generated by Django 2.1 on 2021-01-11 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210108_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborater',
            name='workstation',
        ),
        migrations.AddField(
            model_name='collaborater',
            name='workstation',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ListWorkStation'),
        ),
    ]
