# Generated by Django 2.1 on 2021-01-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210111_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborater',
            name='field',
            field=models.ManyToManyField(blank=True, related_name='collaboraters', to='app.Field'),
        ),
    ]
