# Generated by Django 2.1 on 2021-01-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210111_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborater',
            name='field',
        ),
        migrations.RemoveField(
            model_name='field',
            name='competence',
        ),
        migrations.AddField(
            model_name='competence',
            name='field',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Field'),
        ),
    ]
