# Generated by Django 2.1 on 2021-01-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210111_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('date', models.DateField(max_length=250, unique=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'Domaine',
            },
        ),
    ]
