# Generated by Django 2.1 on 2021-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_listdegree'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborater',
            name='degree',
            field=models.ManyToManyField(blank=True, related_name='collaboraters', to='app.ListDegree'),
        ),
    ]
