# Generated by Django 2.1 on 2021-01-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_collaborater_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdegree',
            name='date',
        ),
    ]
