# Generated by Django 2.1 on 2021-01-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_listdegree_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListDegree',
            new_name='ListCertification',
        ),
        migrations.RenameField(
            model_name='collaborater',
            old_name='degree',
            new_name='certification',
        ),
    ]
