# Generated by Django 2.1 on 2021-01-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210114_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='listinterest',
            name='commentary',
            field=models.CharField(max_length=250, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='listlevel',
            name='commentary',
            field=models.CharField(max_length=250, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='listworkstation',
            name='commentary',
            field=models.CharField(max_length=250, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
    ]
