# Generated by Django 2.1 on 2021-01-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210114_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Société',
            },
        ),
        migrations.AlterModelOptions(
            name='listcertification',
            options={'verbose_name': 'Certifications'},
        ),
        migrations.RemoveField(
            model_name='collaborater',
            name='Society',
        ),
    ]
