# Generated by Django 2.1 on 2021-01-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210115_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborater',
            name='Society',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Society'),
        ),
    ]
