# Generated by Django 2.1 on 2021-01-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210115_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Statut',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='profil',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
