# Generated by Django 2.1 on 2021-01-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_collaborater_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Statut'),
        ),
    ]
