# Generated by Django 2.1 on 2021-01-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_user_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborater',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
