# Generated by Django 2.1 on 2021-01-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_collaborater_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborater',
            name='Extern',
            field=models.BooleanField(default=False, verbose_name='Externe ?'),
        ),
        migrations.AlterField(
            model_name='collaborater',
            name='Firstname',
            field=models.CharField(max_length=200, unique=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='collaborater',
            name='Lastname',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='collaborater',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='collaboraters', to='app.Competence', verbose_name='Compétence'),
        ),
        migrations.AlterField(
            model_name='collaborater',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Society', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='collaborater',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Utilisateur '),
        ),
        migrations.AlterField(
            model_name='collaborater',
            name='workstation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ListWorkStation', verbose_name='Poste de travail'),
        ),
    ]
