# Generated by Django 2.1 on 2021-01-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210118_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='level',
        ),
    ]
