# Generated by Django 2.1 on 2021-01-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210118_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborater',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='collaboraters', to='app.ListInterest'),
        ),
    ]
