# Generated by Django 2.1 on 2021-01-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_collaborater_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='competences', to='app.ListInterest'),
        ),
        migrations.AddField(
            model_name='competence',
            name='level',
            field=models.ManyToManyField(blank=True, related_name='competences', to='app.ListLevel'),
        ),
    ]
