# Generated by Django 2.1 on 2021-01-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210118_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborater',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='level',
        ),
    ]
