# Generated by Django 2.1 on 2021-01-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210118_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ListCompetence',
            },
        ),
        migrations.RemoveField(
            model_name='collaborater',
            name='competences',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='interest',
        ),
        migrations.AddField(
            model_name='listcompetence',
            name='Collaborater',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Collaborater'),
        ),
        migrations.AddField(
            model_name='listcompetence',
            name='Competence',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Competence'),
        ),
        migrations.AddField(
            model_name='listcompetence',
            name='ListInterest',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ListInterest'),
        ),
        migrations.AddField(
            model_name='listcompetence',
            name='ListLevel',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ListLevel'),
        ),
    ]
