# Generated by Django 2.1 on 2021-01-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210120_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListCompetence',
            new_name='ListofCompetence',
        ),
    ]
