# Generated by Django 2.1 on 2021-01-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210121_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListofCompetence',
            new_name='ListCompetence',
        ),
    ]
