# Generated by Django 2.1 on 2021-01-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210121_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcompetence',
            name='Collaborater',
        ),
        migrations.RemoveField(
            model_name='listcompetence',
            name='Competence',
        ),
        migrations.RemoveField(
            model_name='listcompetence',
            name='ListInterest',
        ),
        migrations.RemoveField(
            model_name='listcompetence',
            name='ListLevel',
        ),
        migrations.DeleteModel(
            name='ListCompetence',
        ),
    ]
