# Generated by Django 2.1 on 2021-01-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210121_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collaborater', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Collaborater')),
                ('Competence', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Competence')),
                ('ListInterest', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ListInterest')),
                ('ListLevel', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ListLevel')),
            ],
            options={
                'verbose_name': 'ListCompetence',
            },
        ),
    ]
