# Generated by Django 2.1 on 2021-01-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_listcompetence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListofCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.IntegerField(choices=[(0, 'Aucun'), (1, 'Des notions'), (2, 'Débutant'), (3, 'Intermédiaire'), (4, 'Confirmés')], default=0)),
                ('level', models.IntegerField(choices=[(0, 'Aucun'), (1, 'Des notions'), (2, 'Débutant'), (3, 'Intermédiaire'), (4, 'Confirmés')], default=0)),
                ('Collaborater', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Collaborater')),
                ('Competence', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Competence')),
            ],
            options={
                'verbose_name': 'ListCompetence',
            },
        ),
        migrations.RemoveField(
            model_name='listcompetence',
            name='Collaborater',
        ),
        migrations.RemoveField(
            model_name='listcompetence',
            name='Competence',
        ),
        migrations.RemoveField(
            model_name='listcompetence',
            name='ListInterest',
        ),
        migrations.RemoveField(
            model_name='listcompetence',
            name='ListLevel',
        ),
        migrations.DeleteModel(
            name='ListCompetence',
        ),
        migrations.DeleteModel(
            name='ListInterest',
        ),
        migrations.DeleteModel(
            name='ListLevel',
        ),
        migrations.AddField(
            model_name='collaborater',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='collaboraters', through='app.ListofCompetence', to='app.Competence'),
        ),
    ]
