# Generated by Django 3.1.5 on 2021-01-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210121_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborater',
            options={'verbose_name': 'Collaborateur'},
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name': 'Compétence'},
        ),
        migrations.AlterModelOptions(
            name='listcertification',
            options={'verbose_name': 'Certification'},
        ),
        migrations.AlterModelOptions(
            name='listinterest',
            options={'verbose_name': 'Liste des intérêt'},
        ),
        migrations.AlterModelOptions(
            name='listofcompetence',
            options={'verbose_name': 'Collaborateurs / Competence'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur'},
        ),
    ]
