# Generated by Django 3.1.5 on 2021-01-26 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0040_auto_20210125_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborater',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur '),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
