# Generated by Django 3.1.5 on 2021-02-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20210128_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofcompetence',
            name='Collaborater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.collaborater', verbose_name='Collaborateur'),
        ),
        migrations.AlterField(
            model_name='listofcompetence',
            name='Competence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.competence', verbose_name='Compétence'),
        ),
        migrations.AlterField(
            model_name='listofcompetence',
            name='ListInterest',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.listinterest', verbose_name='Intérêt'),
        ),
        migrations.AlterField(
            model_name='listofcompetence',
            name='ListLevel',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.listlevel', verbose_name='Niveau'),
        ),
    ]
