# Generated by Django 3.1.5 on 2021-02-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210201_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofcompetence',
            name='Collaborater',
        ),
        migrations.AddField(
            model_name='collaborater',
            name='listofcompetence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.listofcompetence', verbose_name='Utilisateur '),
        ),
    ]
