# Generated by Django 3.1.5 on 2021-02-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0046_auto_20210202_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofcompetence',
            name='Collaborater',
        ),
        migrations.AddField(
            model_name='listofcompetence',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
