# Generated by Django 3.1.5 on 2021-02-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20210203_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True, verbose_name='valeur')),
                ('commentary', models.CharField(max_length=250, verbose_name='commentaire')),
            ],
            options={
                'verbose_name': 'Liste des intérêt',
            },
        ),
        migrations.CreateModel(
            name='ListLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True, verbose_name='valeur')),
                ('commentary', models.CharField(max_length=250, verbose_name='commentaire')),
            ],
            options={
                'verbose_name': 'Liste des niveaux',
            },
        ),
        migrations.AlterField(
            model_name='listofcompetence',
            name='ListInterest',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.listinterest', verbose_name='Intérêt'),
        ),
        migrations.AlterField(
            model_name='listofcompetence',
            name='ListLevel',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.listlevel', verbose_name='Niveau'),
        ),
    ]
