# Generated by Django 3.1.5 on 2021-02-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20210203_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listofcompetence',
            options={'verbose_name': 'Utilisateur / Competence'},
        ),
    ]
