# Generated by Django 3.1.5 on 2021-02-15 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0053_auto_20210204_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Extern', models.BooleanField(default=False, verbose_name='Externe ?')),
                ('certification', models.ManyToManyField(blank=True, related_name='collaboraters', to='app.ListCertification')),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.society', verbose_name='Société')),
                ('statut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.statut')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ')),
                ('workstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.listworkstation', verbose_name='Poste de travail')),
            ],
            options={
                'verbose_name': 'Collaborateur',
            },
        ),
        migrations.AlterModelOptions(
            name='listofcompetence',
            options={'verbose_name': 'Competence'},
        ),
        migrations.DeleteModel(
            name='Collaborater',
        ),
    ]
