# Generated by Django 3.1.5 on 2021-02-15 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0054_auto_20210215_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listofcompetence',
            options={'verbose_name': 'Competence des utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil'},
        ),
        migrations.RemoveField(
            model_name='profil',
            name='certification',
        ),
        migrations.AddField(
            model_name='listcertification',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur '),
        ),
    ]
