# Generated by Django 3.1.5 on 2021-02-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20210215_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcertification',
            name='user',
        ),
    ]
