# Generated by Django 3.1.5 on 2021-02-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_listcertification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='statut',
        ),
    ]
