# Generated by Django 3.1.5 on 2021-02-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20210215_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcertification',
            name='user',
        ),
        migrations.AddField(
            model_name='profil',
            name='certification',
            field=models.ManyToManyField(blank=True, related_name='collaboraters', to='app.ListCertification'),
        ),
    ]
