# Generated by Django 3.1.5 on 2021-02-16 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0061_auto_20210215_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='UserProfil',
        ),
    ]
