# Generated by Django 3.1.5 on 2021-02-17 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0062_auto_20210216_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listofcompetence',
            options={'verbose_name': 'Competences des utilisateur'},
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='Extern',
            field=models.BooleanField(default=False, verbose_name="Externe à l'entreprise?"),
        ),
        migrations.CreateModel(
            name='Collaborater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborater', models.BooleanField(default=False, verbose_name='Est un collaborateur ?')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ')),
            ],
            options={
                'verbose_name': 'Collaborateur',
            },
        ),
    ]
