# Generated by Django 3.1.5 on 2021-02-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20210217_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='collaborater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.collaborater', verbose_name='Collaborateur'),
        ),
    ]
