# Generated by Django 3.1.5 on 2021-02-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20210218_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborater',
            old_name='UserProfil',
            new_name='profil',
        ),
    ]
