# Generated by Django 3.1.5 on 2021-02-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20210218_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborater',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofil', verbose_name='Profil '),
        ),
    ]
