# Generated by Django 3.1.5 on 2021-02-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20210218_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborater',
            name='profil',
        ),
        migrations.AddField(
            model_name='userprofil',
            name='collaborater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.collaborater', verbose_name='Collaborateur'),
        ),
    ]
