# Generated by Django 3.1.5 on 2021-02-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20210218_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='collaborater',
        ),
    ]
