# Generated by Django 3.1.5 on 2021-02-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20210218_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='collaborater',
            field=models.BooleanField(default=True, verbose_name='Est un collaborateur ?'),
        ),
        migrations.DeleteModel(
            name='Collaborater',
        ),
    ]
