# Generated by Django 3.1.5 on 2021-02-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0072_auto_20210218_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='collaborater',
        ),
        migrations.CreateModel(
            name='Collaborater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborater', models.BooleanField(default=False, verbose_name='Est un collaborateur ?')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ')),
            ],
            options={
                'verbose_name': 'Collaborateur',
            },
        ),
    ]
