# Generated by Django 3.1.5 on 2021-02-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20210218_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborater',
            name='collaborater',
            field=models.BooleanField(default=True, verbose_name='Etes-vous un collaborateur ?'),
        ),
    ]
